apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: aniiencalada/products
          env:
            - name: MONGO_URI
              value: "mongodb://products-mongo-srv:27017/products"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-name
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: API_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: cafeterias

---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3000
      targetPort: 3000
